// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

#ifndef PROTOBUF_config_2eproto__INCLUDED
#define PROTOBUF_config_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3003000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3003000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
namespace rpcmethod {
class MethodRegist;
class MethodRegistDefaultTypeInternal;
extern MethodRegistDefaultTypeInternal _MethodRegist_default_instance_;
}  // namespace rpcmethod

namespace rpcmethod {

namespace protobuf_config_2eproto {
// Internal implementation detail -- do not call these.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[];
  static const ::google::protobuf::uint32 offsets[];
  static void InitDefaultsImpl();
  static void Shutdown();
};
void AddDescriptors();
void InitDefaults();
}  // namespace protobuf_config_2eproto

// ===================================================================

class MethodRegist : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:rpcmethod.MethodRegist) */ {
 public:
  MethodRegist();
  virtual ~MethodRegist();

  MethodRegist(const MethodRegist& from);

  inline MethodRegist& operator=(const MethodRegist& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MethodRegist& default_instance();

  static inline const MethodRegist* internal_default_instance() {
    return reinterpret_cast<const MethodRegist*>(
               &_MethodRegist_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(MethodRegist* other);

  // implements Message ----------------------------------------------

  inline MethodRegist* New() const PROTOBUF_FINAL { return New(NULL); }

  MethodRegist* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MethodRegist& from);
  void MergeFrom(const MethodRegist& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MethodRegist* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string method = 1;
  void clear_method();
  static const int kMethodFieldNumber = 1;
  const ::std::string& method() const;
  void set_method(const ::std::string& value);
  #if LANG_CXX11
  void set_method(::std::string&& value);
  #endif
  void set_method(const char* value);
  void set_method(const char* value, size_t size);
  ::std::string* mutable_method();
  ::std::string* release_method();
  void set_allocated_method(::std::string* method);

  // int32 id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::int32 id() const;
  void set_id(::google::protobuf::int32 value);

  // int32 optional1 = 3;
  void clear_optional1();
  static const int kOptional1FieldNumber = 3;
  ::google::protobuf::int32 optional1() const;
  void set_optional1(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:rpcmethod.MethodRegist)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr method_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 optional1_;
  mutable int _cached_size_;
  friend struct protobuf_config_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// MethodRegist

// string method = 1;
inline void MethodRegist::clear_method() {
  method_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& MethodRegist::method() const {
  // @@protoc_insertion_point(field_get:rpcmethod.MethodRegist.method)
  return method_.GetNoArena();
}
inline void MethodRegist::set_method(const ::std::string& value) {
  
  method_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:rpcmethod.MethodRegist.method)
}
#if LANG_CXX11
inline void MethodRegist::set_method(::std::string&& value) {
  
  method_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:rpcmethod.MethodRegist.method)
}
#endif
inline void MethodRegist::set_method(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  method_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:rpcmethod.MethodRegist.method)
}
inline void MethodRegist::set_method(const char* value, size_t size) {
  
  method_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:rpcmethod.MethodRegist.method)
}
inline ::std::string* MethodRegist::mutable_method() {
  
  // @@protoc_insertion_point(field_mutable:rpcmethod.MethodRegist.method)
  return method_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* MethodRegist::release_method() {
  // @@protoc_insertion_point(field_release:rpcmethod.MethodRegist.method)
  
  return method_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void MethodRegist::set_allocated_method(::std::string* method) {
  if (method != NULL) {
    
  } else {
    
  }
  method_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), method);
  // @@protoc_insertion_point(field_set_allocated:rpcmethod.MethodRegist.method)
}

// int32 id = 2;
inline void MethodRegist::clear_id() {
  id_ = 0;
}
inline ::google::protobuf::int32 MethodRegist::id() const {
  // @@protoc_insertion_point(field_get:rpcmethod.MethodRegist.id)
  return id_;
}
inline void MethodRegist::set_id(::google::protobuf::int32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:rpcmethod.MethodRegist.id)
}

// int32 optional1 = 3;
inline void MethodRegist::clear_optional1() {
  optional1_ = 0;
}
inline ::google::protobuf::int32 MethodRegist::optional1() const {
  // @@protoc_insertion_point(field_get:rpcmethod.MethodRegist.optional1)
  return optional1_;
}
inline void MethodRegist::set_optional1(::google::protobuf::int32 value) {
  
  optional1_ = value;
  // @@protoc_insertion_point(field_set:rpcmethod.MethodRegist.optional1)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)


}  // namespace rpcmethod

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_config_2eproto__INCLUDED
